<?php
$title = 'Add new Beer';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Beer Name');

// This provides a default CSS class and placeholder text for the artist element:
$brewery_id = $form->get('brewery_id');
$brewery_id->setAttribute('class', 'form-control');
$brewery_id->setAttribute('placeholder', 'Brewery ID');

// This provides a default CSS class and placeholder text for the artist element:
$cat_id = $form->get('cat_id');
$cat_id->setAttribute('class', 'form-control');
$cat_id->setAttribute('placeholder', 'Cat ID');

// This provides a default CSS class and placeholder text for the artist element:
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email ID');

// This provides a default CSS class and placeholder text for the artist element:
$phone_number = $form->get('phone_number');
$phone_number->setAttribute('class', 'form-control');
$phone_number->setAttribute('placeholder', 'Phone Number');



// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('Beer', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php 
	  // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within 
?>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($brewery_id) ?>
    <?= $this->formElement($brewery_id) ?>
    <?= $this->formElementErrors()->render($brewery_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($cat_id) ?>
    <?= $this->formElement($cat_id) ?>
    <?= $this->formElementErrors()->render($cat_id, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($phone_number) ?>
    <?= $this->formElement($phone_number) ?>
    <?= $this->formElementErrors()->render($phone_number, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();